### ISSUE TITLE
Assignment_1_Operators

### ISSUE THREAD

**Issue by AjjaiAravind** [hari-eur/Uthra---Ajjai#1]
Please find the questions in the attached text files. Feel free to reach out in case of any queries.

[Assignment_1_operators.txt](https://github.com/hari-eur/Uthra---Ajjai/files/10824442/Assignment_1_operators.txt)

-Thanks

**Comment by UthraTK** [comment]
I have attached the completed assignment.

[Assignment-1(operators).txt](https://github.com/hari-eur/Uthra---Ajjai/files/10836640/Assignment-1.operators.txt)
